apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidkonkar-deploy
  labels:
    app: sidkonkar-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sidkonkar-app
  template:
    metadata:
      labels:
        app: sidkonkar-app
    spec:
      containers:
      - name: sidkonkar-container
        image: sidkonkar/sa-wd-webapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sidkonkar-np-service
  labels:
    app: sidkonkar-app
spec:
  selector:
    app: sidkonkar-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
